# Generated by Django 6.0.3 on 2026-03-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_original_price_flashsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
